- name: Enable NodeJS
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: App Pre-Req
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Download pem file , Docdb
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.import_tasks:
    file: schema.yml
  when: is_schema_needed